# Site settings
title: Shekhar's Blog
description: 'Shekhars Blog - Programming, Music, Games and perhaps more'
url: 'patnaikshekhar.github.io' 
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Shekhar Patnaik'
  email: patnaikshekhar@gmail.com
  twitter_username: shekharpatnaik
  github_username: patnaikshekhar
  linkedin_username: patnaikshekhar

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
